name: commented-on-issue
on:
  issue_comment:
    types: [created]
jobs:
  update_issue:
    name: "commented-on-issue.move-issue-card"
    runs-on: ubuntu-latest
    steps:
      - name: "adjust-commented-label"
        uses: JEStaubach/action-adjust-commented-label@dev
        with:
          action-token: "${{ secrets.Access_token }}"
      - name: "move-issue-card"
        uses: JEStaubach/action-move-issue-card@dev
        with:
          action-token: "${{ secrets.Access_token }}"
