name: create-issue
on:
  issues:
    types: [opened]
jobs:
  create_issue:
    name: "create-issue"
    runs-on: ubuntu-latest
    steps:
      - name: "greeting"
        uses: JEStaubach/action-greeting@dev
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
          comment-text: "Thanks for opening this issue!"
      - name: "create-once-boards"
        uses: JEStaubach/action-create-once-boards@dev
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "create-once-labels"
        uses: JEStaubach/action-create-once-labels@dev
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "create-card-in-board-column"
        uses: JEStaubach/action-create-card-in-board-column@dev
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
          board-name: "triage"
          column-name: "awaiting review"
