name: create-branch
on: create
jobs:
  create-branch:
    name: "create-branch"
    runs-on: ubuntu-latest
    steps:
      - name: "create-branch"
        uses: JEStaubach/action-create-branch@dev
        if: github.event.ref_type == 'branch'
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
          repo: "${{ github.repository }}"
          ref: "${{ github.ref }}"
