name: unassign-issue
on:
  issues:
    types: [unassigned]
jobs:
  update_issue:
    name: "github-projects.update-issue.move-issue-card"
    runs-on: ubuntu-latest
    steps:
      - name: "move-issue-card"
        uses: actions/checkout@v1
        with:
          repository: JEstaubach/actions
          ref: refs/heads/dev
      - name: "get-deps"
        run: |
          pwd
          dir
          cd github-projects/update-issue/move-issue-card
          npm ci
          node index.js
          env:
            ACTION_TOKEN: "${{ secrets.Access_token }}"
